import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import HeaderRouter from "./ui/Header/HeaderRouter";

const inter = Inter({
  subsets: ["greek"],
  weight: ["200", "400", "600", "800", "900"],
});

export const metadata: Metadata = {
  title: "My Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#FAFAFA] `}>
        <HeaderRouter />
        {children}
      </body>
    </html>
  );
}
